version: "3.8"

services:

  nginx:
    container_name: app.tecpoint.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    links:
      - php
      - mysql
    networks:
      - tecpoint-dev
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www/html:/var/www/html
    restart: unless-stopped

  php:
    container_name: app.tecpoint.php
    image: php:8.0-fpm
    build: './php/'
    expose:
       - 9000
    links:
       - mysql
    networks:
      - tecpoint-dev
    volumes:
      - ./www/html:/var/www/html
    restart: unless-stopped

  mysql:
    container_name: app.tecpoint.mysql
    build: './mysql/'
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./www/html:/var/www/html
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pwd
    networks:
      - tecpoint-dev
    restart: unless-stopped

networks:
  tecpoint-dev:
    driver: bridge
